services:
  # It is not recommended to expose anything to the outside world
  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes: 
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
