services:
  # It is not recommended to expose anything to the outside world
  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  rabbit:
    image: rabbitmq:alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - -q
        - check_running
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s