#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
	CREATE USER $APOSTGRES_USER WITH LOGIN PASSWORD '$APOSTGRES_PASSWORD';
    CREATE DATABASE $APOSTGRES_DB OWNER $APOSTGRES_USER;
    CREATE EXTENSION pg_trgm;
EOSQL