"""Initial commit

Revision ID: 4f0e88d960e5
Revises: 
Create Date: 2022-08-03 13:20:14.419669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0e88d960e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExpiringThreads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GuildConfigurations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('jail_channel', sa.BigInteger(), nullable=True),
    sa.Column('jail_role', sa.BigInteger(), nullable=True),
    sa.Column('mute_role', sa.BigInteger(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.Column('prefixes', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('suspicious_usernames', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('public_tags', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('strict_anti_phishing', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PhishingUrls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PunishmentCounters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('counter', sa.BigInteger(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('Punishments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_name', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suggestions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachments', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.String(), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('translated_string', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Translations')
    op.drop_table('Tags')
    op.drop_table('Suggestions')
    op.drop_table('Punishments')
    op.drop_table('PunishmentCounters')
    op.drop_table('PhishingUrls')
    op.drop_table('GuildConfigurations')
    op.drop_table('ExpiringThreads')
    # ### end Alembic commands ###
