"""Change LevelRewards level to BigInteger

Revision ID: 59318486cff2
Revises: 1735e3e17c9b
Create Date: 2023-04-10 22:13:24.369355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59318486cff2'
down_revision = '1735e3e17c9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LevelRewards', sa.Column('level', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LevelRewards', 'level')
    # ### end Alembic commands ###
