"""Added RoleChangeQueue table

Revision ID: 6758102fff31
Revises: 59318486cff2
Create Date: 2023-06-27 13:02:49.519576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6758102fff31'
down_revision = '59318486cff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleChangeQueue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleChangeQueue')
    # ### end Alembic commands ###
