"""Remove mute_role column from guild configurations

Revision ID: 6bda5ebb3b42
Revises: 574961e0a853
Create Date: 2023-03-03 12:58:59.791181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bda5ebb3b42'
down_revision = '574961e0a853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuildConfigurations', 'mute_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuildConfigurations', sa.Column('mute_role', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
