"""Remove progress_character column and add theme_name instead

Revision ID: fbec2237a3a7
Revises: 56d14b370f9b
Create Date: 2023-08-05 15:02:28.297386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec2237a3a7'
down_revision = '56d14b370f9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLevels', sa.Column('theme_name', sa.String(), nullable=True))
    op.drop_column('UserLevels', 'progress_character')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLevels', sa.Column('progress_character', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('UserLevels', 'theme_name')
    # ### end Alembic commands ###
