"""Update user levels table

Revision ID: 58da93f13d53
Revises: 6bda5ebb3b42
Create Date: 2023-04-10 20:57:40.974339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da93f13d53'
down_revision = '6bda5ebb3b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLevels', sa.Column('xp_to_next_level', sa.BigInteger(), server_default='100', nullable=True))
    op.drop_column('UserLevels', 'messages_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLevels', sa.Column('messages_sent', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('UserLevels', 'xp_to_next_level')
    # ### end Alembic commands ###
