"""Added suggestion related options to GuildConfiguration table

Revision ID: eab3567ad381
Revises: 6758102fff31
Create Date: 2023-07-19 13:50:19.279796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab3567ad381'
down_revision = '6758102fff31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuildConfigurations', sa.Column('suggestion_system_active', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('GuildConfigurations', sa.Column('suggestion_channel', sa.BigInteger(), nullable=True))
    op.add_column('GuildConfigurations', sa.Column('suggestion_threads_enabled', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuildConfigurations', 'suggestion_threads_enabled')
    op.drop_column('GuildConfigurations', 'suggestion_channel')
    op.drop_column('GuildConfigurations', 'suggestion_system_active')
    # ### end Alembic commands ###
