"""Remove suggestions table

Revision ID: f1af566cd6d0
Revises: 82ed2ac5afea
Create Date: 2025-07-29 18:48:59.932388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1af566cd6d0'
down_revision = '82ed2ac5afea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Suggestions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('suggestion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_submitted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attachments', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Suggestions_pkey'))
    )
    # ### end Alembic commands ###
