"""Add date_created to the Reminder table

Revision ID: 08d143919da6
Revises: 98f472898da8
Create Date: 2023-08-24 16:13:56.539756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d143919da6'
down_revision = '98f472898da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reminders', sa.Column('date_created', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reminders', 'date_created')
    # ### end Alembic commands ###
