"""Create progress_character column for UserLevels table

Revision ID: 56d14b370f9b
Revises: eab3567ad381
Create Date: 2023-08-02 16:55:33.718871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d14b370f9b'
down_revision = 'eab3567ad381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLevels', sa.Column('progress_character', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserLevels', 'progress_character')
    # ### end Alembic commands ###
