"""Add appeal_url for guild configs

Revision ID: 574961e0a853
Revises: 3c8d28d954d5
Create Date: 2023-03-03 12:29:55.485977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574961e0a853'
down_revision = '3c8d28d954d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuildConfigurations', sa.Column('appeal_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuildConfigurations', 'appeal_url')
    # ### end Alembic commands ###
