"""Add roles row to linked accounts table

Revision ID: 8c8a4f8ad03f
Revises: fbec2237a3a7
Create Date: 2023-08-22 15:07:23.628001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8a4f8ad03f'
down_revision = 'fbec2237a3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LinkedAccounts', sa.Column('roles', sa.ARRAY(sa.BigInteger()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LinkedAccounts', 'roles')
    # ### end Alembic commands ###
