"""Add date_wage_last_redeemed column to LinkedAccounts

Revision ID: d701f9500009
Revises: 5a4e82566a92
Create Date: 2022-08-10 16:40:38.144849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd701f9500009'
down_revision = '5a4e82566a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LinkedAccounts', sa.Column('date_wage_last_redeemed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LinkedAccounts', 'date_wage_last_redeemed')
    # ### end Alembic commands ###
