"""Add punishing_moderators boolean to guild configuration and removing PhishingUrls table

Revision ID: e4ab9de39520
Revises: d701f9500009
Create Date: 2022-12-06 19:27:48.832391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ab9de39520'
down_revision = 'd701f9500009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PhishingUrls')
    op.add_column('GuildConfigurations', sa.Column('punishing_moderators', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuildConfigurations', 'punishing_moderators')
    op.create_table('PhishingUrls',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"PhishingUrls_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PhishingUrls_pkey')
    )
    # ### end Alembic commands ###
