name: Docker Image CI

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image and tag it
      run: ./build.sh

    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push to ghcr.io
      run: docker image push --all-tags ghcr.io/justanyones/pidroid
